### ISSUE TITLE
Need help with private keys

### ISSUE THREAD

**Issue by mrspartak** [remorses/mongoke#2]
Hey sir, your app is amazing, but one thing I can't figure yet out. 
I have a collection with flags:
-show [true|false]
-deleted [true|false]
-pinned [true|false]

First two of them are private. That mean, I need every graphql request they be equal as show=true AND deleted=false, and I can't expose them.
The third flag is public, so I will expose it and use in queries. Do I need to use pipeline key? I didn't see any examples of usage.

**Comment by mrspartak** [comment]
Oh, I guess I found how to do it. That is just mongo pipeline. 
pipeline: [{$match: {show: true, deleted: false}}]

You need to set an [open collective](https://opencollective.com/) link for your project

**Comment by mrspartak** [comment]
Oh, another question: this is mongo, so I have nested objects. For example, I have an object that describes cover and an array of objects room

How I should describe schema in this situation? 
```
item {
  _id: 1,
  show: true,
  deleted: false,
  pinned: false,
  cover: {
    url: 'example.com',
    path: '/i/123.jpeg'
  },
  rooms: [
    {
       name: 'bathroom',
       photos: [
         {
           url: 'example.com',
           path: '/i/123.jpeg'
         }
       ]
    }
  ]
}
```

**Comment by remorses** [comment]
You can use nested objects in the graphql schema:
```gql

type Item {
    _id: ObjectId
    deleted: Boolean
    pinned: Boolean
    cover: Cover
    rooms: [Room]
}

type Cover {
    url: String
    path: String
}

type Room {
    name: String
}
```

Instead if your objects use references you can use the `relations` in the config

**Comment by remorses** [comment]
I have an open collective now if you want to give some ❤️
