### ISSUE TITLE
[Improvement] Better plurals

### ISSUE THREAD

**Issue by khaosdoctor** [remorses/mongoke#4]
This is just an improvement I thought about while demoing on a live stream today. But we had a type called `Activity` and Mongoke made it `Activitys` which is a wrong plural, should be "Activities"

**Comment by remorses** [comment]
There are too many exceptions to plural names, like the plural of Money would not be Moneys or Moneis but Money

What about adding a ‘Nodes’ postfix, like ‘ActivityNodes’?

**Comment by khaosdoctor** [comment]
I changed to contribution, this way we made "contributions" so things got quite ok. Isn't there a library that would help you do the plurals?

**Comment by remorses** [comment]
I removed plurals in version `1.4`, now to get more items you can use `ContributionNodes` or `ActivityNodes`

pull the image again to get the latest

The api can now be considered stable and won't have any breaking change in the near future
